import { img } from "@/lib/constants";
const slugify = (value) => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const RAW_MENU_ITEMS = [
  [
    "Pav Bhaji",
    "starters",
    "Street Favourite",
    150,
    34507155,
    2,
    1,
    1,
    1,
    "Mumbai-style buttery mashed vegetable bhaji with toasted, buttered pav."
  ],
  [
    "Paneer Tikka",
    "kebabs",
    "North Indian",
    210,
    20395267,
    2,
    1,
    1,
    0,
    "Char-grilled paneer cubes in a smoky tandoori marinade, finished with lemon."
  ],
  [
    "Hara Bhara Kebab",
    "kebabs",
    "North Indian",
    160,
    29173093,
    0,
    0,
    0,
    0,
    "Golden spinach-and-potato patties, crisp outside, soft inside, with mint chutney."
  ],
  [
    "Chilli Paneer",
    "chinese",
    "Indo-Chinese",
    220,
    30604608,
    3,
    0,
    1,
    0,
    "Wok-tossed paneer, peppers and onion in a glossy, fiery soy-chilli glaze."
  ],
  [
    "Veg Manchurian Dry",
    "chinese",
    "Indo-Chinese",
    170,
    35066808,
    2,
    0,
    0,
    0,
    "Crisp vegetable dumplings tossed with soy, garlic and a hint of chilli."
  ],
  [
    "Crispy Corn",
    "starters",
    "Quick Bites",
    180,
    35066808,
    1,
    0,
    0,
    0,
    "Golden-fried sweet corn dusted with tangy chaat masala."
  ],
  [
    "Veg Spring Rolls",
    "starters",
    "Indo-Chinese",
    160,
    5031949,
    1,
    0,
    0,
    0,
    "Hand-rolled crispy rolls stuffed with crunchy vegetables, served hot."
  ],
  [
    "Paneer 65",
    "starters",
    "South Indian",
    210,
    30604608,
    3,
    0,
    0,
    0,
    "South-Indian style fried paneer with curry leaves, green chilli and yogurt."
  ],
  [
    "Hot & Sour Soup",
    "soups-salads",
    "Indo-Chinese",
    130,
    12737816,
    2,
    0,
    0,
    0,
    "Peppery, tangy broth with crunchy vegetables — a warming start."
  ],
  [
    "Sweet Corn Soup",
    "soups-salads",
    "Indo-Chinese",
    120,
    11188417,
    0,
    0,
    0,
    0,
    "Silky, comforting corn soup with delicate seasoning."
  ],
  [
    "Manchow Soup",
    "soups-salads",
    "Indo-Chinese",
    130,
    30604608,
    2,
    0,
    0,
    0,
    "Spicy Indo-Chinese soup topped with crispy noodles."
  ],
  [
    "Veg Clear Soup",
    "soups-salads",
    "Indo-Chinese",
    120,
    12737816,
    0,
    0,
    0,
    0,
    "Light, aromatic vegetable broth with garden vegetables."
  ],
  [
    "Green Salad",
    "soups-salads",
    "Fresh",
    90,
    8845416,
    0,
    0,
    0,
    0,
    "Crisp cucumber, onion, tomato and carrot with a lemon dressing."
  ],
  [
    "Veg Fried Rice",
    "chinese",
    "Indo-Chinese",
    150,
    7593267,
    1,
    0,
    0,
    0,
    "Wok-tossed rice with vegetables and a whisper of soy."
  ],
  [
    "Schezwan Fried Rice",
    "chinese",
    "Indo-Chinese",
    170,
    12669168,
    3,
    0,
    0,
    0,
    "Fiery schezwan rice with crunchy vegetables."
  ],
  [
    "Veg Manchurian Gravy",
    "chinese",
    "Indo-Chinese",
    180,
    35066808,
    2,
    1,
    1,
    0,
    "Veg dumplings simmered in a rich, garlicky soy gravy."
  ],
  [
    "Chilli Mushroom",
    "chinese",
    "Indo-Chinese",
    210,
    30604608,
    3,
    0,
    0,
    0,
    "Button mushrooms in a sticky, spicy chilli sauce."
  ],
  [
    "Hakka Noodles",
    "noodles",
    "Indo-Chinese",
    140,
    2347311,
    1,
    0,
    1,
    0,
    "Smoky wok-fried noodles with crisp vegetables."
  ],
  [
    "Schezwan Noodles",
    "noodles",
    "Indo-Chinese",
    170,
    2456435,
    3,
    0,
    0,
    0,
    "Noodles tossed in a bold, spicy schezwan sauce."
  ],
  [
    "Chilli Garlic Noodles",
    "noodles",
    "Indo-Chinese",
    160,
    2456434,
    2,
    0,
    0,
    0,
    "Garlic-forward noodles with a warm chilli kick."
  ],
  [
    "Singapore Noodles",
    "noodles",
    "Indo-Chinese",
    180,
    28895977,
    2,
    0,
    0,
    0,
    "Curried, lightly spiced noodles with colourful vegetables."
  ],
  [
    "Dal Tadka",
    "north-indian",
    "North Indian",
    170,
    11188417,
    1,
    0,
    0,
    0,
    "Slow-simmered lentils tempered with ghee, garlic and cumin."
  ],
  [
    "Dal Makhani",
    "north-indian",
    "North Indian",
    190,
    11188417,
    0,
    1,
    1,
    0,
    "Creamy black lentils cooked low and slow with butter."
  ],
  [
    "Kadhai Paneer",
    "north-indian",
    "North Indian",
    230,
    12737816,
    2,
    0,
    0,
    0,
    "Paneer and peppers tossed in a robust kadhai masala."
  ],
  [
    "Shahi Paneer",
    "north-indian",
    "North Indian",
    240,
    11188417,
    0,
    0,
    0,
    0,
    "Soft paneer in a rich, mildly sweet cashew-cream gravy."
  ],
  [
    "Veg Kolhapuri",
    "north-indian",
    "North Indian",
    200,
    12737816,
    3,
    0,
    0,
    0,
    "Bold, spicy mixed-vegetable curry from the Kolhapur kitchen."
  ],
  [
    "Malai Kofta",
    "north-indian",
    "North Indian",
    230,
    11188417,
    0,
    1,
    0,
    0,
    "Melt-in-the-mouth kofta in a silky tomato-cashew gravy."
  ],
  [
    "Chana Masala",
    "north-indian",
    "North Indian",
    170,
    11188417,
    1,
    0,
    0,
    0,
    "Punjabi-style chickpeas in a tangy, spiced tomato gravy."
  ],
  [
    "Mix Veg",
    "north-indian",
    "North Indian",
    180,
    12737816,
    1,
    0,
    0,
    0,
    "Seasonal vegetables in a homely onion-tomato masala."
  ],
  [
    "Aloo Gobhi",
    "north-indian",
    "North Indian",
    170,
    12737816,
    1,
    0,
    0,
    0,
    "A classic of potatoes and cauliflower, dry-spiced and fragrant."
  ],
  [
    "Paneer Rajwadi",
    "paneer-specials",
    "North Indian",
    240,
    35993886,
    2,
    1,
    1,
    1,
    "Paneer simmered in a royal, richly spiced rajwadi gravy."
  ],
  [
    "Paneer Maharani",
    "paneer-specials",
    "North Indian",
    250,
    11188417,
    1,
    1,
    1,
    1,
    "A regal cashew-and-saffron gravy with tender paneer."
  ],
  [
    "Paneer Butter Masala",
    "paneer-specials",
    "North Indian",
    230,
    11188417,
    1,
    1,
    1,
    1,
    "The crowd favourite — silky tomato-butter gravy with paneer."
  ],
  [
    "Paneer Tikka Masala",
    "paneer-specials",
    "North Indian",
    240,
    30858420,
    2,
    0,
    0,
    0,
    "Smoked paneer tikka folded into a creamy onion masala."
  ],
  [
    "Paneer Lababdar",
    "paneer-specials",
    "North Indian",
    240,
    28674541,
    1,
    0,
    0,
    0,
    "Paneer in a deep, tangy tomato-onion gravy with cream."
  ],
  [
    "Paneer Bhurji",
    "paneer-specials",
    "North Indian",
    200,
    12737816,
    1,
    0,
    0,
    0,
    "Scrambled paneer cooked with onion, tomato and spices."
  ],
  [
    "Veg Biryani",
    "rice-biryani",
    "North Indian",
    190,
    12669168,
    1,
    1,
    1,
    1,
    "Fragrant basmati layered with vegetables, mint and whole spices."
  ],
  [
    "Paneer Biryani",
    "rice-biryani",
    "North Indian",
    210,
    35287417,
    1,
    0,
    0,
    0,
    "Aromatic biryani with soft paneer and saffron-kissed rice."
  ],
  [
    "Jeera Rice",
    "rice-biryani",
    "North Indian",
    140,
    7593267,
    0,
    0,
    0,
    0,
    "Basmati tempered with roasted cumin."
  ],
  [
    "Steamed Rice",
    "rice-biryani",
    "North Indian",
    110,
    7593267,
    0,
    0,
    0,
    0,
    "Plain steamed basmati."
  ],
  [
    "Veg Pulao",
    "rice-biryani",
    "North Indian",
    150,
    12669168,
    0,
    0,
    0,
    0,
    "Lightly spiced basmati with garden vegetables."
  ],
  [
    "Butter Naan",
    "breads",
    "North Indian",
    45,
    28125427,
    0,
    0,
    0,
    0,
    "Soft tandoor naan brushed with butter."
  ],
  [
    "Garlic Naan",
    "breads",
    "North Indian",
    55,
    28125427,
    0,
    0,
    0,
    0,
    "Naan topped with garlic and fresh coriander."
  ],
  [
    "Cheese Naan",
    "breads",
    "North Indian",
    75,
    20446413,
    0,
    0,
    0,
    0,
    "Stuffed naan with molten cheese."
  ],
  [
    "Tandoori Roti",
    "breads",
    "North Indian",
    20,
    6183640,
    0,
    0,
    0,
    0,
    "Whole-wheat flatbread from the tandoor."
  ],
  [
    "Butter Roti",
    "breads",
    "North Indian",
    25,
    6183640,
    0,
    0,
    0,
    0,
    "Tandoori roti with a touch of butter."
  ],
  [
    "Laccha Paratha",
    "breads",
    "North Indian",
    45,
    20446402,
    0,
    0,
    0,
    0,
    "Flaky, layered whole-wheat paratha."
  ],
  [
    "Idli Sambar",
    "south-indian",
    "South Indian",
    110,
    20422128,
    0,
    0,
    1,
    0,
    "Steamed rice cakes with sambar and chutneys."
  ],
  [
    "Medu Vada",
    "south-indian",
    "South Indian",
    120,
    20422132,
    1,
    0,
    0,
    0,
    "Crisp golden lentil vadas with sambar."
  ],
  [
    "Plain Dosa",
    "south-indian",
    "South Indian",
    100,
    20422129,
    0,
    0,
    0,
    0,
    "Crisp golden dosa with sambar and chutneys."
  ],
  [
    "Uttapam",
    "south-indian",
    "South Indian",
    140,
    20408455,
    1,
    0,
    0,
    0,
    "Thick, soft rice-lentil pancake with onion and tomato."
  ],
  [
    "Onion Rava Dosa",
    "south-indian",
    "South Indian",
    150,
    20422133,
    1,
    0,
    0,
    0,
    "Lacy, crisp rava dosa with onion."
  ],
  [
    "Masala Dosa",
    "dosa-specials",
    "South Indian",
    130,
    20422138,
    1,
    1,
    1,
    1,
    "Crisp golden dosa with spiced potato masala, sambar and chutneys."
  ],
  [
    "Mysore Masala Dosa",
    "dosa-specials",
    "South Indian",
    160,
    20422133,
    3,
    0,
    0,
    0,
    "Dosa spread with fiery mysore chutney and potato masala."
  ],
  [
    "Jini Dosa",
    "dosa-specials",
    "South Indian",
    190,
    20422121,
    2,
    1,
    1,
    1,
    "Street-famous loaded dosa with cheese, veggies and tangy house sauces."
  ],
  [
    "Jini Paneer Dosa",
    "dosa-specials",
    "South Indian",
    210,
    20422121,
    2,
    1,
    0,
    1,
    "Jini dosa loaded with extra paneer and cheese."
  ],
  [
    "Cheese Burst Dosa",
    "dosa-specials",
    "South Indian",
    200,
    20422133,
    1,
    1,
    1,
    1,
    "A molten, pull-apart cheese core inside a crackling dosa."
  ],
  [
    "Paneer Rajwadi Dosa",
    "dosa-specials",
    "South Indian",
    210,
    20422123,
    3,
    0,
    0,
    0,
    "Dosa stuffed with rajwadi-style spicy paneer."
  ],
  [
    "AK-47 Dosa",
    "dosa-specials",
    "South Indian",
    220,
    20422129,
    4,
    1,
    0,
    1,
    "Fiery schezwan-loaded dosa for serious heat lovers."
  ],
  [
    "Bhurj Khalifa Dosa",
    "dosa-specials",
    "South Indian",
    230,
    20422123,
    3,
    1,
    1,
    1,
    "Our tallest loaded dosa with paneer bhurji and cheese."
  ],
  [
    "Schezwan Dosa",
    "dosa-specials",
    "South Indian",
    170,
    20422133,
    3,
    0,
    0,
    0,
    "Dosa with a bold schezwan punch."
  ],
  [
    "Butter Masala Dosa",
    "dosa-specials",
    "South Indian",
    140,
    20422138,
    1,
    0,
    0,
    0,
    "Classic dosa with a generous butter finish."
  ],
  [
    "Pani Puri",
    "delhi-chaat",
    "Chaat",
    70,
    9738980,
    2,
    0,
    0,
    0,
    "Crisp puris with tangy, spicy pani."
  ],
  [
    "Sev Puri",
    "delhi-chaat",
    "Chaat",
    80,
    9738980,
    1,
    0,
    0,
    0,
    "Crisp puris topped with chutneys, sev and onion."
  ],
  [
    "Bhel Puri",
    "delhi-chaat",
    "Chaat",
    80,
    9738980,
    1,
    0,
    0,
    0,
    "Puffed rice tossed with chutneys and crunchy sev."
  ],
  [
    "Dahi Puri",
    "delhi-chaat",
    "Chaat",
    90,
    9738980,
    0,
    0,
    0,
    0,
    "Puri cups filled with cool yogurt and chutneys."
  ],
  [
    "Samosa Chaat",
    "delhi-chaat",
    "Chaat",
    90,
    5031949,
    1,
    0,
    1,
    0,
    "Crushed samosa with yogurt, chutneys and sev."
  ],
  [
    "Papdi Chaat",
    "delhi-chaat",
    "Chaat",
    90,
    9738980,
    1,
    0,
    0,
    0,
    "Crisp papdi with yogurt, chutneys and spices."
  ],
  [
    "Margherita",
    "pizza",
    "Italian",
    180,
    1552635,
    0,
    0,
    0,
    0,
    "Classic tomato, mozzarella and basil."
  ],
  [
    "Paneer Tikka Pizza",
    "pizza",
    "Italian",
    230,
    11975887,
    2,
    1,
    1,
    1,
    "Tandoori paneer, onion and capsicum on a cheesy base."
  ],
  [
    "Cheese Burst Pizza",
    "pizza",
    "Italian",
    220,
    29173086,
    0,
    0,
    1,
    0,
    "A molten cheese-stuffed crust."
  ],
  [
    "Farmhouse",
    "pizza",
    "Italian",
    240,
    1552635,
    0,
    0,
    0,
    0,
    "Loaded with onion, capsicum, corn and tomato."
  ],
  [
    "Tandoori Paneer Pizza",
    "pizza",
    "Italian",
    240,
    11975887,
    2,
    0,
    0,
    0,
    "Smoky tandoori paneer with a spicy drizzle."
  ],
  [
    "Corn & Cheese",
    "pizza",
    "Italian",
    200,
    29173086,
    0,
    0,
    0,
    0,
    "Sweet corn and a blanket of mozzarella."
  ],
  [
    "White Sauce Pasta",
    "pasta",
    "Italian",
    180,
    1438672,
    0,
    0,
    1,
    0,
    "Creamy béchamel pasta with herbs."
  ],
  [
    "Red Sauce Pasta",
    "pasta",
    "Italian",
    180,
    15813476,
    1,
    0,
    0,
    0,
    "Tangy tomato-basil pasta."
  ],
  [
    "Mix Sauce Pasta",
    "pasta",
    "Italian",
    190,
    3214160,
    1,
    0,
    0,
    0,
    "The best of both — creamy and tangy."
  ],
  [
    "Alfredo Pasta",
    "pasta",
    "Italian",
    200,
    29173118,
    0,
    0,
    0,
    0,
    "Rich, cheesy alfredo with garlic bread."
  ],
  [
    "Grilled Veg Sandwich",
    "sandwiches",
    "Quick Bites",
    120,
    8023677,
    0,
    0,
    0,
    0,
    "Toasted sandwich with garden vegetables."
  ],
  [
    "Cheese Corn Sandwich",
    "sandwiches",
    "Quick Bites",
    140,
    30346820,
    0,
    0,
    0,
    0,
    "Gooey cheese and sweet corn, toasted."
  ],
  [
    "Paneer Tikka Sandwich",
    "sandwiches",
    "Quick Bites",
    160,
    20422166,
    2,
    0,
    0,
    0,
    "Spiced paneer tikka filling, grilled."
  ],
  [
    "Club Sandwich",
    "sandwiches",
    "Quick Bites",
    150,
    8023677,
    0,
    0,
    0,
    0,
    "A triple-decker loaded with veggies."
  ],
  [
    "Classic Maggi",
    "maggi",
    "Quick Bites",
    60,
    2347311,
    0,
    0,
    1,
    0,
    "Everyone's favourite, cooked just right."
  ],
  [
    "Masala Maggi",
    "maggi",
    "Quick Bites",
    70,
    2456435,
    1,
    0,
    0,
    0,
    "Extra masala, extra comfort."
  ],
  [
    "Cheese Maggi",
    "maggi",
    "Quick Bites",
    90,
    2456434,
    0,
    0,
    0,
    0,
    "Creamy, cheesy twist on classic Maggi."
  ],
  [
    "Butter Maggi",
    "maggi",
    "Quick Bites",
    70,
    2347311,
    0,
    0,
    0,
    0,
    "Tossed with butter and a sprinkle of pepper."
  ],
  [
    "Chocolate Brownie",
    "desserts",
    "Desserts",
    120,
    33312980,
    0,
    1,
    1,
    0,
    "Warm, fudgy brownie, baked fresh daily."
  ],
  [
    "Brownie with Ice Cream",
    "desserts",
    "Desserts",
    160,
    16785689,
    0,
    1,
    0,
    0,
    "Warm brownie with a scoop of vanilla ice cream."
  ],
  [
    "Gulab Jamun (2 pc)",
    "desserts",
    "Desserts",
    60,
    16785689,
    0,
    0,
    0,
    0,
    "Soft, syrup-soaked classic."
  ],
  [
    "Hot Chocolate Fudge",
    "desserts",
    "Desserts",
    140,
    14753356,
    0,
    0,
    0,
    0,
    "Molten chocolate fudge with nuts."
  ],
  [
    "Ice Cream Scoop",
    "desserts",
    "Desserts",
    80,
    14753356,
    0,
    0,
    0,
    0,
    "Choice of vanilla, chocolate or strawberry."
  ],
  [
    "Chocolate Shake",
    "shakes",
    "Beverages",
    130,
    18142621,
    0,
    1,
    0,
    0,
    "Thick, cold chocolate shake."
  ],
  [
    "Oreo Shake",
    "shakes",
    "Beverages",
    140,
    18142622,
    0,
    1,
    0,
    0,
    "Cookies-and-cream blended shake."
  ],
  [
    "Strawberry Shake",
    "shakes",
    "Beverages",
    130,
    5005919,
    0,
    0,
    0,
    0,
    "Fruity, creamy strawberry shake."
  ],
  [
    "Mango Shake",
    "shakes",
    "Beverages",
    120,
    5005919,
    0,
    0,
    0,
    0,
    "Seasonal mango shake, blended thick."
  ],
  [
    "Cold Coffee",
    "beverages",
    "Beverages",
    110,
    2789328,
    0,
    1,
    1,
    1,
    "Frothy, chilled coffee — the house classic."
  ],
  [
    "Mint Mojito",
    "beverages",
    "Beverages",
    120,
    4051265,
    0,
    1,
    1,
    1,
    "Fresh mint, lime and crushed ice."
  ],
  [
    "Virgin Mojito",
    "beverages",
    "Beverages",
    110,
    2698886,
    0,
    0,
    0,
    0,
    "Cool, sparkling mint-lime refresher."
  ],
  [
    "Fresh Lime Soda",
    "beverages",
    "Beverages",
    80,
    5370563,
    0,
    0,
    0,
    0,
    "Sweet or salted lime with soda."
  ],
  [
    "Masala Chaas",
    "beverages",
    "Beverages",
    50,
    5370563,
    0,
    0,
    0,
    0,
    "Spiced buttermilk with roasted cumin."
  ],
  [
    "Sweet Lassi",
    "beverages",
    "Beverages",
    80,
    5005919,
    0,
    0,
    0,
    0,
    "Thick, chilled sweet yogurt lassi."
  ],
  [
    "Hot Coffee",
    "beverages",
    "Beverages",
    60,
    36662612,
    0,
    0,
    0,
    0,
    "A warm cup, brewed fresh."
  ],
  [
    "Hot Tea",
    "beverages",
    "Beverages",
    40,
    36662612,
    0,
    0,
    0,
    0,
    "Indian masala chai."
  ],
  [
    "Couple Combo",
    "combos",
    "Combos",
    499,
    11188417,
    1,
    1,
    0,
    0,
    "Two mains, breads and beverages for two."
  ],
  [
    "Combo for 2",
    "combos",
    "Combos",
    399,
    7593267,
    1,
    1,
    0,
    0,
    "A quick, satisfying meal for two."
  ],
  [
    "Combo for 4",
    "combos",
    "Combos",
    799,
    34507155,
    1,
    1,
    0,
    0,
    "Family-style spread for four."
  ],
  [
    "Combo for 6",
    "combos",
    "Combos",
    1199,
    4262169,
    1,
    1,
    0,
    0,
    "A full spread for bigger tables."
  ]
];
export const FALLBACK_MENU_ITEMS = RAW_MENU_ITEMS.map((it, index) => {
  const [name, category, cuisine, price, imageId, spicyLevel, recommended, bestseller, signature, description] = it;
  return { id: index + 1, name, slug: slugify(name), description, category, cuisine, price: String(price), image: img(imageId), vegetarian: true, spicyLevel, recommended: Boolean(recommended), bestseller: Boolean(bestseller), signature: Boolean(signature), available: true };
});
export const FALLBACK_CATEGORIES = [
  {
    "id": 1,
    "name": "Recommended",
    "slug": "recommended",
    "icon": "⭐",
    "sortOrder": 1
  },
  {
    "id": 2,
    "name": "Starters",
    "slug": "starters",
    "icon": "🥟",
    "sortOrder": 2
  },
  {
    "id": 3,
    "name": "Pizza",
    "slug": "pizza",
    "icon": "🍕",
    "sortOrder": 3
  },
  {
    "id": 4,
    "name": "Kebabs",
    "slug": "kebabs",
    "icon": "🍢",
    "sortOrder": 4
  },
  {
    "id": 5,
    "name": "Chinese",
    "slug": "chinese",
    "icon": "🥢",
    "sortOrder": 5
  },
  {
    "id": 6,
    "name": "Soups & Salads",
    "slug": "soups-salads",
    "icon": "🍲",
    "sortOrder": 6
  },
  {
    "id": 7,
    "name": "North Indian",
    "slug": "north-indian",
    "icon": "🍛",
    "sortOrder": 7
  },
  {
    "id": 8,
    "name": "Paneer Specials",
    "slug": "paneer-specials",
    "icon": "🧀",
    "sortOrder": 8
  },
  {
    "id": 9,
    "name": "Rice & Biryani",
    "slug": "rice-biryani",
    "icon": "🍚",
    "sortOrder": 9
  },
  {
    "id": 10,
    "name": "Breads",
    "slug": "breads",
    "icon": "🫓",
    "sortOrder": 10
  },
  {
    "id": 11,
    "name": "South Indian",
    "slug": "south-indian",
    "icon": "🥞",
    "sortOrder": 11
  },
  {
    "id": 12,
    "name": "Dosa Specials",
    "slug": "dosa-specials",
    "icon": "🌯",
    "sortOrder": 12
  },
  {
    "id": 13,
    "name": "Delhi Chaat",
    "slug": "delhi-chaat",
    "icon": "🫕",
    "sortOrder": 13
  },
  {
    "id": 14,
    "name": "Pasta",
    "slug": "pasta",
    "icon": "🍝",
    "sortOrder": 14
  },
  {
    "id": 15,
    "name": "Noodles",
    "slug": "noodles",
    "icon": "🍜",
    "sortOrder": 15
  },
  {
    "id": 16,
    "name": "Sandwiches",
    "slug": "sandwiches",
    "icon": "🥪",
    "sortOrder": 16
  },
  {
    "id": 17,
    "name": "Maggi",
    "slug": "maggi",
    "icon": "🍥",
    "sortOrder": 17
  },
  {
    "id": 18,
    "name": "Desserts",
    "slug": "desserts",
    "icon": "🍨",
    "sortOrder": 18
  },
  {
    "id": 19,
    "name": "Shakes",
    "slug": "shakes",
    "icon": "🥤",
    "sortOrder": 19
  },
  {
    "id": 20,
    "name": "Beverages",
    "slug": "beverages",
    "icon": "🍹",
    "sortOrder": 20
  },
  {
    "id": 21,
    "name": "Combos",
    "slug": "combos",
    "icon": "🎁",
    "sortOrder": 21
  }
];
export const FALLBACK_GALLERY = [
  { id: 1, image: img(26729397), caption: "Warm, wood-toned dining room", category: "Restaurant", sortOrder: 0 },
  { id: 2, image: img(20422138), caption: "Golden masala dosa with sambar and chutneys", category: "Food", sortOrder: 1 },
  { id: 3, image: img(20422121), caption: "Jini dosa, loaded and tossed", category: "Dosa Specials", sortOrder: 2 },
  { id: 4, image: img(11188417), caption: "Paneer butter masala, straight from the kitchen", category: "Food", sortOrder: 3 },
  { id: 5, image: img(29309717), caption: "Soft lighting and patterned walls", category: "Restaurant", sortOrder: 4 },
  { id: 6, image: img(1552635), caption: "Fresh from the pizza oven", category: "Food", sortOrder: 5 },
  { id: 7, image: img(34507155), caption: "Pav bhaji, buttered and bold", category: "Food", sortOrder: 6 },
  { id: 8, image: img(20422123), caption: "Bhurj Khalifa — our showstopper", category: "Dosa Specials", sortOrder: 7 },
  { id: 9, image: img(4051265), caption: "Mint mojito over crushed ice", category: "Beverages", sortOrder: 8 },
  { id: 10, image: img(12669168), caption: "Fragrant veg biryani", category: "Food", sortOrder: 9 },
  { id: 11, image: img(17109124), caption: "Table settings and wooden panels", category: "Restaurant", sortOrder: 10 },
  { id: 12, image: img(1438672), caption: "Creamy white-sauce pasta", category: "Food", sortOrder: 11 },
  { id: 13, image: img(33312980), caption: "Warm brownie with ice cream", category: "Food", sortOrder: 12 },
  { id: 14, image: img(18142621), caption: "Thick chocolate shake", category: "Beverages", sortOrder: 13 },
  { id: 15, image: img(3184177), caption: "Tables made for sharing", category: "Guests", sortOrder: 14 },
  { id: 16, image: img(4262169), caption: "Family dinners at Ayodhya", category: "Guests", sortOrder: 15 },
  { id: 17, image: img(20422133), caption: "Cheese burst dosa, pulled apart", category: "Dosa Specials", sortOrder: 16 },
  { id: 18, image: img(36662612), caption: "Masala chai in clay cups", category: "Beverages", sortOrder: 17 },
  { id: 19, image: img(6876621), caption: "A quiet corner for a long meal", category: "Restaurant", sortOrder: 18 },
  { id: 20, image: img(3184184), caption: "Celebrations, done warm", category: "Events", sortOrder: 19 },
];
export const FALLBACK_OFFERS = [
  { id: 1, slug: "family-feast", title: "Family Feast", description: "A generous sharing spread made for family tables — mains, breads, beverages and something sweet.", image: img(4262169), badge: "Family Pick", ctaLabel: "Explore Menu", ctaLink: "/menu", validFrom: "", validUntil: "", active: true },
  { id: 2, slug: "dosa-special", title: "Dosa Spotlight", description: "Try one of our signature loaded dosas with sambar and house chutneys.", image: img(20422138), badge: "House Favourite", ctaLabel: "See Dosas", ctaLink: "/menu?cat=dosa-specials", validFrom: "", validUntil: "", active: true },
  { id: 3, slug: "dessert-finish", title: "Sweet Finish", description: "End your meal with a warm brownie, ice cream or one of our chilled shakes.", image: img(33312980), badge: "Desserts", ctaLabel: "View Menu", ctaLink: "/menu?cat=desserts", validFrom: "", validUntil: "", active: true },
];
export const FALLBACK_REVIEWS = [
  { id: 1, name: "Local Diner", rating: 5, review: "A comfortable family dining experience with plenty of variety across Indian and Indo-Chinese favourites.", source: "Guest", date: "", approved: true },
  { id: 2, name: "Betul Food Lover", rating: 5, review: "The dosa selection and paneer dishes make this an easy choice when everyone at the table wants something different.", source: "Guest", date: "", approved: true },
  { id: 3, name: "Family Guest", rating: 4, review: "Warm ambience, broad menu and a relaxed setting that works well for family meals and groups.", source: "Guest", date: "", approved: true },
];
